print('-' * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama : Alya Setya Paramita')
print('NPM  : 21083010046')
print('-' * 35)
print('notes')
print('Halo Dunia!')
print('Ini adalah skrip Bash pertamaku di Linux')
