#!/bin/bash
echo "-----------------------------------"
echo "Tugas 1 SISOP Kelas-A"
echo "-----------------------------------"
echo "Nama : Alya Setya Paramita"
echo "NPM  : 21083010046"
echo "-----------------------------------"
echo "notes"
echo "-----------------------------------"
echo "Halo Dunia!"
echo "Ini adalah skrip Bash pertamaku di Linux"
